import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/Component/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-screen bg-[#f8fafc] w-full">
        <Sidebar />
        <div className="flex-1">{children}</div>
      </body>
    </html>
  );
}
